resources:
  - name: 10s
    type: time
    source: {interval: 10s}
  - name: github
    type: git
    source:
      uri: https://github.com/danielsiwiec/concourse-demo.git
      branch: master

jobs:
- name: hello-world
  plan:
  - get: 10s
    trigger: true
  - get: github
    trigger: true
  - task: install
    file: github/install.yml
  - task: test
    file: github/test.yml
